server:
  port: 8585
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    password: '0804'
    url: jdbc:oracle:thin:@//localhost:1521/XE
    username: segunis
  jackson:
    time-zone: America/Guatemala
  jpa:
    show-sql: true
    
